name: Build and Push to ACR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login mernregistry123.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and Push Frontend
      run: |
        docker build -t mernregistry123.azurecr.io/frontend:latest ./frontend
        docker push mernregistry123.azurecr.io/frontend:latest

    - name: Build and Push Backend
      run: |
        docker build -t mernregistry123.azurecr.io/backend:latest ./backend
        docker push mernregistry123.azurecr.io/backend:latest
