name: Build and Push to ACR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: mernregistry123-f7axhhhngaa2cxf0.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Frontend
      run: |
        docker build -t mernregistry123-f7axhhhngaa2cxf0.azurecr.io/frontend:latest ./frontend
        docker push mernregistry123-f7axhhhngaa2cxf0.azurecr.io/frontend:latest

    - name: Build and Push Backend
      run: |
        docker build -t mernregistry123-f7axhhhngaa2cxf0.azurecr.io/backend:latest ./backend
        docker push mernregistry123-f7axhhhngaa2cxf0.azurecr.io/backend:latest
